repos:
  - repo: local
    hooks:
      - id: black
        name: Run black formatter
        entry: black
        language: system
        types: [python]
        args: ["--line-length=88"]
        files: \.py$
        exclude: ^(venv|\.venv|build|dist)/

      - id: isort
        name: Run isort import sorter
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]
        files: \.py$
        exclude: ^(venv|\.venv|build|dist)/
