[project]
name = "forglove-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kszheng", email = "2436809937@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
forglove-helper = "forglove_helper:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
